# ---- STORM CLIENT ----
storm.name=Storm Client
storm.version=1.0.0
storm.package=xyz.stormclient

# Primary target of this repository
minecraft.version=1.8.9
forge.version=1.8.9-11.15.1.2318-1.8.9
mappings.channel=stable
mappings.version=22-1.8.9

org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
